version: "3.8"

services:
  web:
    build: .
    container_name: "todo-app-container"
    ports:
      - "5000:5000"

  db:
    image: "postgres"
    container_name: "todo-db-container"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker123"
